### PR TITLE
Dummy connection changes

### PR DESCRIPTION
**Pull request by jkeen**
When writing an acceptance test, the audio wasn't being incremented because of the `Ember.checkTestWaiters` thing. I think we can skip this (???) if we handle the tick better. Hifi's test pass with this change, plus `wnyc-web-client` plus `new-sounds-web-client`.

### CODE REVIEW

**Comment by noslouch** [comment]
But now tests are failing with this change. What if `startTicking` used `Ember.run.later` to do the interval? I think the original problem was that tests would fail on and off because fake audio files didn't stop ticking after a test ended. I was trying to force them to stop in test mode, but I think checkWaiters is not reliable in this case.

**Comment by jkeen** [comment]
The good news is you're right about the tests failing, the bad news is that I don't think they're failing specifically due to these changes. I just triggered a rebuild on master and they're failing on there too. 💣 

Something changed. Something is up.

**Comment by jkeen** [comment]
Also, we tried the `Ember.run.later` initially, but I think the ember crowd recommends not to do that in tests because tests wouldn't complete, so I switched to timeout

https://github.com/emberjs/ember.js/issues/3008

**Comment by jkeen** [comment]
Closing this since the landscape has changed, and i think the testing issues are bigger than this little change.

**Pull request closed without merging**
